{
  /*eslint-disable @next/next/no-img-element*/
}
import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

interface Pokemon {
  id: number;
  name: string;
  image: string;
}

const Home: NextPage = () => {
  const [pokemons, setPokemons] = useState<Array<Pokemon>>([]);

  useEffect(() => {
    async function getPokemon() {
      const resp = await fetch(
        "https://arindampal-0.github.io/pokemon-api/index.json"
      );
      setPokemons((await resp.json()) as Array<Pokemon>);
    }

    getPokemon();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Pokemon List</h2>
      <div className={styles.grid}>
        {pokemons.map((pokemon) => (
          <div className={styles.card} key={pokemon.id}>
            <Link href={`/pokemon/${pokemon.id}`}>
              <a>
                <img
                  src={`https://arindampal-0.github.io/pokemon-api/${pokemon.image}`}
                  alt={pokemon.name}
                />
                <h3>{pokemon.name}</h3>
              </a>
            </Link>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Home;
