import { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

interface Pokemon {
  id: number;
  name: string;
  image: string;
}

const Home: NextPage = () => {
  const [pokemon, setPokemon] = useState<Array<Pokemon>>([]);

  useEffect(() => {
    async function getPokemon() {
      const resp = await fetch(
        "https://arindampal-0.github.io/pokemon-api/index.json"
      );
      setPokemon(await resp.json());
    }

    getPokemon();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Pokemon List</h1>
      <div>{JSON.stringify(pokemon)}</div>
    </div>
  );
};

export default Home;
